image: dokku-alt/base

script:
- sed -i 's/linux-image-extra-virtual, //g' deb/dokku-alt/DEBIAN/control
- make install
- tests/run_localhost

notify:
  email:
    recipients:
    - ayufan@ayufan.eu
    on_success: "true"
    on_failure: "true"
  webhook:
    urls:
    - $$GITTER_SERVICE
    on_success: true
    on_failure: true
  slack:
    webhook_url: $$SLACK_SERVICE
    on_started: true
    on_success: true
    on_failure: true
